FROM vault.habana.ai/gaudi-docker/1.14.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.1:latest

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install cron -y && \
    apt-get install openssh-server -y && \
    apt-get install net-tools -y && \
    apt-get install wget -y && \
    apt-get install vim -y && \
    apt-get install curl -y && \
    apt-get install python3-pip -y && \
    apt-get install unzip -y && \
    apt-get install unixodbc unixodbc-dev -y

# setting ssh
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

#set image time zone
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

RUN TZ=Asia/Taipei && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata

# set for workdir
WORKDIR /root
RUN mkdir /root/code/

# upgrade & install package
COPY requirements.txt /root/requirements.txt
RUN pip install --upgrade pip && \
    apt-get install libaio1 -y && \
    pip install -r requirements.txt --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org \
    pip install git+https://github.com/openai/CLIP.git


#load code
# COPY ./app /root/code/app

EXPOSE 22
EXPOSE 8001
